name: ppd599
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bokeh
  - cartopy
  - contextily
  - dill
  - folium
  - geopandas=0.8.*
  - ipython=7.10.*
  - jupyterlab
  - mapclassify
  - osmnx  # =1.0.*
  - pandana
  - pandas=1.1.*
  - psycopg2
  - pysal
  - python=3.8.*
  - rasterio
  - rtree=0.9.*
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - urbanaccess
